server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chinaxlt?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456xlt
    hikari:
      max-lifetime: 60000

## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.chinaxlt.study.pojo  # 注意：对应实体类的路径
